### ISSUE TITLE
Use of the HTTP proxy functionality breaks remapping

### ISSUE THREAD

**Issue by chaoticsmol** [equalitie/bundler-proxy#1]
**MOVED FROM BUNDLER**

> When useProxy is set to true, the Host header is no longer rewritten appropriately.
> 
> I believe this is related to requests's use of CONNECT tunneling: https://www.npmjs.com/package/request#proxies"

@nosmo

**Comment by chaoticsmol** [comment]
I've whipped up the following test code to see if I can reproduce this behavior, but I don't seem to have a problem.

``` javascript
var bundler = require('./bundler');
var urllib = require('url');
var http = require('http');

function handler(req, res) {
  console.log('Got request for ' + req.url);
  var make = new bundler.Bundler(req.url);

  make.on('originalRequest', function (options, next) {
    console.log('### in originalRequest, OPTIONS = ', options);
    next(null, options);
  });

  make.on('originalReceived', bundler.replaceImages);

  // Reverse proxy
  make.on('resourceRequest', function (options, next) {
    var url = urllib.parse(options.url);
    if (!options.hasOwnProperty('headers')) {
      options.headers = {};
    }
    console.log('hostname = ' + url.hostname);
    if (url.hostname === 'nosmo.me') {
      options.url = urllib.resolve(url.protocol + '//' + 'fulltimeinter.net', url.path);
      options.headers['Host'] = url.hostname;
    }
    console.log('Set reverse proxy');
    next(null, options);
  });

  make.on('resourceRequest', function (options, next) {
    console.log('### in resourceRequest, before proxyTo, OPTIONS = ' , options);
    next(null, options)
  });

  make.on('resourceRequest', bundler.proxyTo('http://localhost:9009'));

  make.on('resourceRequest', function (options, next) {
    console.log('### in resourceRequest, after proxyTo, OPTIONS = ' , options);
    next(null, options)
  });

  make.bundle(function (err, bundle) {
    if (err) {
      console.log('ERROR', err.message);
    } else {
      console.log('SUCCESS done');
      res.writeHead(200, {'Content-Type': 'text/html'});
      res.write(bundle);
      res.end();
    }
  });
}

http.createServer(handler).listen(9009, '127.0.0.1', function () {
  console.log('Starting server');
});
console.log('Server listening on port 9009');
```

I then used CURL as such:

```
curl -x http://127.0.0.1:9009 http://nosmo.me
```

The output I get is as follows:

```
Server listening on port 9009
Starting server
Got request for http://nosmo.me/
### in originalRequest, OPTIONS =  { url: 'http://nosmo.me/',
  strictSSL: false,
  rejectUnauthorized: false }
hostname = nosmo.me
Set reverse proxy
### in resourceRequest, before proxyTo, OPTIONS =  { url: 'http://fulltimeinter.net/horse_ebooks_large_verge_medium_landscape.jpg',
  encoding: null,
  headers: { Host: 'nosmo.me' } }
### in resourceRequest, after proxyTo, OPTIONS =  { url: 'http://fulltimeinter.net/horse_ebooks_large_verge_medium_landscape.jpg',
  encoding: null,
  headers: { Host: 'nosmo.me' },
  proxy: 'http://localhost:9009' }
Got request for http://fulltimeinter.net/horse_ebooks_large_verge_medium_landscape.jpg
### in originalRequest, OPTIONS =  { url: 'http://fulltimeinter.net/horse_ebooks_large_verge_medium_landscape.jpg',
  strictSSL: false,
  rejectUnauthorized: false }
SUCCESS done
SUCCESS done
```

You see that the request for horse_ebooks_... has the hostname `fulltimeinter.net` and that `headers['Host']` is indeed `"nosmo.me"`.

I'm not really sure how I can reproduce the error you had.

**Comment by chaoticsmol** [comment]
@nosmo Are you running Node 0.12? Apparently request.js doesn't work with that version yet.
https://github.com/request/request

**Comment by nosmo** [comment]
... yes I am. D'oh, I'll downgrade. Sorry for wasting your time.

**Comment by nosmo** [comment]
request now supports v0.12 but I'm still seeing this issue, reopening :(

**Comment by chaoticsmol** [comment]
Bill and I have tried to reproduce this error again using a remap from an equalitie website to its origin.  The remapping worked as expected.  Can you give us some steps to reproduce?

**Comment by nosmo** [comment]
Okay, we'll talk about this later off-thread I'm sure but some info: 

Proxy is running on localhost, port 80. 
It works: 
`$ http_proxy=localhost:80 curl google.com`
from /var/log/trafficserver/deflect.log: 
`127.0.0.1 - [05/Jun/2015:10:31:21 -0000] "GET /- HTTP/1.1" http google.com 302 258 "curl/7.38.0" TCP_MISS text/html google.com 4 http://google.com/`

After setting useProxy to true and proxyAddress to "http://localhost:80", fetches work normally when doing commands akin to `curl localhost:9008/?url=http://google.com`. The proxy log indicates appropriate use of the proxy for both the base page and the resources upon it. 

However, if my remaps.json file contains the following while using the proxy: 

```
{
   "state.gov": "72.166.186.151",
}
```

Then requests sent to `localhost:9008/?url=http://state.gov` lose their Host header and are simply sent to the origin IP address: 
`127.0.0.1 - [05/Jun/2015:10:51:08 -0000] "GET /index.htm HTTP/1.1" http 72.166.186.151 302 301 "-" TCP_MISS text/html 72.166.186.151 90 http://72.166.186.151/index.htm`

Just a side not - When testing, it's important to make sure that tests are done against a host that won't do wildcard redirects to the appropriate host (as with google.com for example).

**Comment by chaoticsmol** [comment]
I believe I have been able to verify that this issue is happening in the proxy server you're using and not bundler-proxy.  My procedure is as follows:
1. Run [log-dest.js](https://github.com/equalitie/bundler-proxy/blob/master/log-dest.js) to act as a proxy server (that doesn't actually proxy)
2. Set `useProxy` to `true` and `proxyAddress` to `127.0.0.1:9009` in `psconfig.js`
3. Add the key-value pair `"nosmo.me": "fulltimeinter.net"` to `remaps.js`
4. Run `node[js] proxyserver.js --config <path-to-psconfig>`
5. Run `curl http://localhost:9008?url=http://nosmo.me`

I observe the following:
1. Curl outputs `Acknowledged`, which is the plainttext response log-dest returns, as  expected
2. log-dest outputs:
   1. The URL is `http://fulltimeinter.net`
   2. The Host header is still `nosmo.me`

**Comment by chaoticsmol** [comment]
If I had to make a guess, I'd say the more sophisticated proxy server you were using didn't like that the host isn't a completely specified URL (missing the http(s) schema), and so decided to set Host to a valid address and just uses the request URL.

**Correction**

I tried making sure that the Host always has the protocol provided, and verified with my log-dest server that it was present in requests forwarded by the proxy server.  Despite this modification, the logs have shown that the Host header is still rewritten to be the same as the requested URL by the time Apache trafficserver receives it.  Is there any kind of remap rule in trafficserver that could be doing it?

**Comment by nosmo** [comment]
Confirmed that proxying works properly when testing with tinyproxy and a remap. My apologies, this has been a big waste of your time. 

Tangential but the Host header should never have the protocol specified, not sure if that works with any server
